### ISSUE TITLE
Grin++ crashing when validating state on setup

### ISSUE THREAD

**Issue by philippnagel** [GrinPlusPlus/GrinPlusPlusMobile#18]
Device: LG G5
OS: LineageOS 11 (18.1)

When starting Grin++ the first time steps 1 and 2 work, after step 3 the app crashes.

Is there any way to extract e.g. logs via ADB?

**Comment by davidtavarez** [comment]
Which version are you using? Where did you download the APK from?

**Comment by philippnagel** [comment]
Whooops, latest directly from Google Play.

**Comment by davidtavarez** [comment]
Would you mind to download the APK from Keybase? You will need to uninstall
the one you have installed from Google Play Store.

The URL is this https://keybase.pub/dtavarez/grin%2B%2B/android90/apk/0.3.0/

Someone else reported that after using that APK he was able to sync
properly.

**Comment by philippnagel** [comment]
The version from Google Play is versioned as 0.2.0, will try it and report back!

**Comment by philippnagel** [comment]
Still no change. Tried it on two different smartphones, both running Android 11.

To rule out network issues I installed the app on Linux and it synced successfully.

Can I e.g. export logs via ADB?

**Comment by davidtavarez** [comment]
The best way to test this is to download the binary directly from here: https://keybase.pub/dtavarez/grin%2B%2B/android90/binary/testing/

`libgrin.so` is the node itself.

Install Termux from here: https://termux.com/ and download the node. 

Change the permissions like this: `chmod a+x libgrin.so`

Run it (`./libgrin.so`) and let it open.

It is important to disable the power optimization for Termux (and Grin++) to avoid the OS kills the app.

**Comment by sceaduwe** [comment]
I'm having the same issue. Crashes past 25% when validating.
Tried it in Termux, and it also crashed. Here's the [Node.log](https://github.com/GrinPlusPlus/GrinPlusPlusMobile/files/9312659/Node.log) from Termux.
And the android crash log from the GUI.
```
type: crash
osVersion: google/sargo/sargo:12/SP2A.220505.006/2022080900:user/release-keys
package: com.grinplusplus.mobile:7
process: com.grinplusplus.mobile

android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at GrinPlusPlus.Droid.GrinNodeService.OnStartCommand (Android.Content.Intent intent, Android.App.StartCommandFlags flags, System.Int32 startId) [0x00000] in <749f2fa2014f4cf4931c62eadc723ebf>:0 
  at Android.App.Service.n_OnStartCommand_Landroid_content_Intent_II (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_intent, System.Int32 native_flags, System.Int32 startId) [0x0000f] in <5c456b408d8d48a3b7a20e508a799cc6>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.30(intptr,intptr,intptr,int,int)
	at com.grinplusplus.mobile.GrinNodeService.n_onStartCommand(Native Method)
	at com.grinplusplus.mobile.GrinNodeService.onStartCommand(Unknown Source:0)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4712)
	at android.app.ActivityThread.access$2000(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

Device: Pixel 3a
OS: GrapheneOS

**Comment by davidtavarez** [comment]
Use f-droid to install it https://forum.grin.mw/t/installing-grin-for-android-using-f-droid/9732

**Comment by sceaduwe** [comment]
that's what i did

**Comment by davidtavarez** [comment]
I'll check that.
